source "https://rubygems.org"

ruby "3.1.2"

gem "builder"
gem "middleman"
gem "middleman-aria_current"
gem "middleman-inline_svg"
gem "middleman-autoprefixer"
gem "middleman-minify-html"
gem "middleman-livereload"
gem 'middleman-dotenv'
gem 'middleman-favicon-maker'
# gem 'middleman-meta-tags', git: 'https://github.com/gabrielecanepa/middleman-meta-tags'
# gem 'middleman-pry'
gem 'middleman-robots'

# Development
gem 'pry-byebug'
# TODO: Fix middleman-pry
# https://github.com/AndrewKvalheim/middleman-pry
# gem "middleman-pry"
gem "redcarpet"
