source "https://rubygems.org"

ruby "3.1.2"

gem "builder"
gem "middleman"
gem "middleman-aria_current"
gem "middleman-inline_svg"
gem "middleman-autoprefixer"
gem "middleman-minify-html"
gem "redcarpet"
