source "https://rubygems.org"

ruby "3.1.2"

gem "builder"
gem "middleman"
gem "middleman-aria_current"
gem "middleman-inline_svg"
gem "middleman-autoprefixer"
gem "middleman-minify-html"
gem "middleman-livereload"
# TODO: Fix middleman-pry
# https://github.com/AndrewKvalheim/middleman-pry
# gem "middleman-pry"
gem "redcarpet"
