version: 2

jobs:
  build:
    docker:
      - image: circleci/ruby:3.1.2-node

    steps:
      - checkout

      - restore_cache:
          key: middleman-project-{{ arch }}-{{ checksum "Gemfile.lock" }}

      - run:
          name: Install Ruby dependencies
          command: bundle install --path vendor/bundle

      - save_cache:
          key: middleman-project-{{ arch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - restore_cache:
          keys:
            - middleman-project-{{ arch }}-{{ checksum "package-lock.json" }}
            - middleman-project-{{ arch }}-

      - run:
          name: Install npm dependencies
          command: npm install

      - save_cache:
          key: middleman-project-{{ arch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/usr/local/lib/node_modules

      - run:
          name: Setup the environment
          command: cp .env.sample .env

      - run:
          name: Build Middleman site
          command: bundle exec middleman build --verbose
